[tool.nbqa.addopts]
flake8 = [
    "--max-line-length=120",
    "--extend-ignore=E203",
    "--per-file-ignores=docker/work/answer/ans_preprocess_knock_SQL.ipynb:E402"
]

[tool.nbqa.exclude]
flake8 = "docker/work/preprocess_knock_"
mypy = "docker/work/preprocess_knock_"
pylint = "docker/work/preprocess_knock_"
ruff = "docker/work/preprocess_knock_"
