name: format

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

permissions: { }

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          fetch-depth: 0
      - name: Get Python version
        id: get_python_version
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: |
          chmod -R 777 docker/
          docker compose up -d --wait
          echo "version=$(docker compose exec notebook python --version | sed -e 's/Python //g')" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-python@v5.1.0
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          python-version: ${{ steps.get_python_version.outputs.version }}
          cache: pipenv
      - name: Install packages
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: |
          pip install "$(grep -oE 'pipenv[^ ]+' dockerfiles/notebook/Dockerfile)"
          pipenv install
      - run: sed -i -e "s/python=.*/python=$(yq -p toml -oy '.requires.python_version' Pipfile)/g" environment.yml
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
      - uses: dev-hato/actions-diff-pr-management@v1.1.12
        if: success() || failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: fix-format
          pr-title-prefix: formatを修正しました。
