name: format

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          fetch-depth: 0
      - name: Get Python version
        id: get_python_version
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: |
          docker compose up -d --wait
          version="$(docker compose exec notebook python --version | sed -e 's/Python //g')"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "minor_version=$(echo "$version" | sed -e 's/\([0-9]*\.[0-9]*\).*/\1/g')" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-python@v5.1.0
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          python-version: ${{ steps.get_python_version.outputs.version }}
          cache: pipenv
      - run: sed -i -e "s/python_version = \".*\"/python_version = \"${{ steps.get_python_version.outputs.minor_version }}\"/g" Pipfile
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
      - run: sed -i -e "s/python=.*/python=${{ steps.get_python_version.outputs.minor_version }}/g" environment.yml
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
      - run: |
          pip install "$(grep -oE 'pipenv[^ ]+' dockerfiles/notebook/Dockerfile)"
          pipenv install
          pipenv install $(pipenv run pip freeze | grep ipython==) $(pipenv run pip freeze | grep ipykernel==)
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
      - uses: dev-hato/actions-diff-pr-management@v1.1.12
        if: success() || failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: fix-format
          pr-title-prefix: format修正
