###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

permissions:
  statuses: write
  contents: write
  pull-requests: write

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - master
  pull_request:

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - uses: actions/setup-python@v5.5.0
        with:
          python-version: 3.11
          cache: pipenv

      - run: |
          pip install --no-cache-dir -r requirements.txt
          pipenv install
          cp -r .venv /home/runner/work/_temp/_github_workflow/.venv

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_HTML: false
          VALIDATE_HTML_PRETTIER: false
          FILTER_REGEX_EXCLUDE: docker/.jupyter/jupyter_lab_config.py
          VALIDATE_SQLFLUFF: false
          FIX_JUPYTER_NBQA_BLACK: true
          FIX_JUPYTER_NBQA_ISORT: true
          FIX_JUPYTER_NBQA_RUFF: true
          FIX_JSON_PRETTIER: true
      - uses: dev-hato/actions-diff-pr-management@v1.1.12
        if: success() || failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: fix-super-linter
